repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Update this to point to a specific version you want
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --config-file ./mypy.ini
        language: system
        types: [python]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # Print the number of files as a sanity-check
        verbose: true
        args:
          [
            --namespace-packages,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --disallow-untyped-calls,
          ]
