name: PyTest

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "dev"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Run Pytest
        run: |
          pytest udao
